Repository Cache-and-Cookies/HiTea, pull requests merged in 2020-12, with the labels that each got.

#55 fixed #40 by adding a sitemap using the django Sitemap package and by…
  HiTea/HiTea/settings.py
  HiTea/store/sitemaps.py
  HiTea/store/urls.py
  HiTea/store/views.py
Labels: enhancement

#61 Favicon.ico is now a .ico instead of .png!!
  Documentation.md
  HiTea/static/images/favicon.ico
  HiTea/store/templates/store/base.html
Labels: enhancement

#62 Food HWY, Hungry Pand, Lanyangyang, Skip the dishes logos are optimized now
  HiTea/static/images-optimize/fantuan.jpg
  HiTea/static/images-optimize/foodhwy.jpg
  HiTea/static/images-optimize/hungrypanda.jpg
  HiTea/static/images-optimize/lanyangyang.jpg
  HiTea/static/images-optimize/skipthedishes.jpg
  HiTea/static/images-optimize/ubereats.jpg
  HiTea/static/images/HiTea Logo.png
  HiTea/static/images/fantuan.png
  HiTea/static/images/foodhwy.png
  HiTea/static/images/hungrypanda.jpg
  HiTea/static/images/lanyangyang.jpg
  HiTea/static/images/skipthedishes.jpg
  HiTea/static/images/ubereats.png
  HiTea/store/templates/store/home.html
Labels: bug

#67 min instance of 1; db connection time now 1 hour
  HiTea/HiTea/settings.py
  HiTea/app.yaml
Labels: enhancement

#68 changed jquery integrity
  HiTea/store/templates/store/base.html
Labels: bug

#69 Load Testing Findings
  HiTea/.gcloudignore
  HiTea/load_testing/images/number_of_users_1608874320.png
  HiTea/load_testing/images/number_of_users_1608875264.png
  HiTea/load_testing/images/response_times_(ms)_1608874320.png
  HiTea/load_testing/images/response_times_(ms)_1608875264.png
  HiTea/load_testing/images/total_requests_per_second_1608874320.png
  HiTea/load_testing/images/total_requests_per_second_1608875264.png
  HiTea/load_testing/locustfile.py
  HiTea/load_testing/requirements.txt
  HiTea/load_testing/results.md
Labels: enhancement, help wanted

#71 fixed #63 by adding structured data for products in home.html
  HiTea/store/templates/store/base.html
  HiTea/store/templates/store/home.html
Labels: enhancement

#72 changed product name from Bubble Tea to HiTea so Google Search Consol…
  HiTea/store/templates/store/home.html
Labels: enhancement

#73 minor changes to structured data: google search console is still crying
  HiTea/store/templates/store/home.html
Labels: enhancement
